# Generated by Django 2.2.6 on 2019-10-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0003_auto_20190816_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='img',
        ),
    ]
